#pragma once

const std::string NOMINAL_INPUT =
        "(\n"
        "    (Capture image-01.raw\n"
        "        (id 6zlQW000LK) (name 1KDVQwb) (timestamp 2019-10-23T11:50:04-04:00)\n"
        "        (capture_settings\n"
        "            ((mode idle) (frequency 2400) (fps 33)\n"
        "             (exposure 9750) (gain_r  250) (gain_g 50.2) (gain_b 5876.123))\n"
        "        )\n"
        "        (coordinates\n"
        "            ((latitude 45.5169557) (longitude -73.580725) (altitude -6300000))\n"
        "        )\n"
        "    )\n"
        ")";

const std::string NOMINAL_EXPECTED_OUTPUT =
        "(\n"
        "\t(\n"
        "\t\tSymbol: Capture\n"
        "\t\tSymbol: image-01.raw\n"
        "\t\t(\n"
        "\t\t\tSymbol: id\n"
        "\t\t\tSymbol: 6zlQW000LK\n"
        "\t\t)\n"
        "\t\t(\n"
        "\t\t\tSymbol: name\n"
        "\t\t\tSymbol: 1KDVQwb\n"
        "\t\t)\n"
        "\t\t(\n"
        "\t\t\tSymbol: timestamp\n"
        "\t\t\tSymbol: 2019-10-23T11:50:04-04:00\n"
        "\t\t)\n"
        "\t\t(\n"
        "\t\t\tSymbol: capture_settings\n"
        "\t\t\t(\n"
        "\t\t\t\t(\n"
        "\t\t\t\t\tSymbol: mode\n"
        "\t\t\t\t\tSymbol: idle\n"
        "\t\t\t\t)\n"
        "\t\t\t\t(\n"
        "\t\t\t\t\tSymbol: frequency\n"
        "\t\t\t\t\tInteger: 2400\n"
        "\t\t\t\t)\n"
        "\t\t\t\t(\n"
        "\t\t\t\t\tSymbol: fps\n"
        "\t\t\t\t\tInteger: 33\n"
        "\t\t\t\t)\n"
        "\t\t\t\t(\n"
        "\t\t\t\t\tSymbol: exposure\n"
        "\t\t\t\t\tInteger: 9750\n"
        "\t\t\t\t)\n"
        "\t\t\t\t(\n"
        "\t\t\t\t\tSymbol: gain_r\n"
        "\t\t\t\t\tInteger: 250\n"
        "\t\t\t\t)\n"
        "\t\t\t\t(\n"
        "\t\t\t\t\tSymbol: gain_g\n"
        "\t\t\t\t\tFloating: 50.2\n"
        "\t\t\t\t)\n"
        "\t\t\t\t(\n"
        "\t\t\t\t\tSymbol: gain_b\n"
        "\t\t\t\t\tFloating: 5876.12\n"
        "\t\t\t\t)\n"
        "\t\t\t)\n"
        "\t\t)\n"
        "\t\t(\n"
        "\t\t\tSymbol: coordinates\n"
        "\t\t\t(\n"
        "\t\t\t\t(\n"
        "\t\t\t\t\tSymbol: latitude\n"
        "\t\t\t\t\tFloating: 45.517\n"
        "\t\t\t\t)\n"
        "\t\t\t\t(\n"
        "\t\t\t\t\tSymbol: longitude\n"
        "\t\t\t\t\tFloating: -73.5807\n"
        "\t\t\t\t)\n"
        "\t\t\t\t(\n"
        "\t\t\t\t\tSymbol: altitude\n"
        "\t\t\t\t\tInteger: -6300000\n"
        "\t\t\t\t)\n"
        "\t\t\t)\n"
        "\t\t)\n"
        "\t)\n"
        ")\n";